# NGINX Configuration Generator

# Main variables
[main]
banner = "NGINX Configuration Generator"
version = "1.2"
url = "https://github.com/fabriziofiorucci/NGINX-Config-Generator"

# Templates
[templates]
root_dir = "../templates"
nginxmain = "nginx-conf/nginx.conf"
mimetypes = "nginx-conf/mime.types"

httpconf = "http.tmpl"
streamconf = "stream.tmpl"
configmap = "configmap.tmpl"

# API Server configuration
[apiserver]
host = "0.0.0.0"
port = 5000

# Redis backend for CI/CD automation
[redis]
host = "127.0.0.1"
port = 6379

# Staged configuration for NGINX Management Suite
[nms]
config_dir = '/etc/nginx'
certs_dir = '/etc/nginx/ssl'

# Time to wait to get status after committing a staged config
staged_config_publish_waittime = 5

nap_policies_dir = '/etc/nginx/waf/policies'
nap_logformats_dir = '/etc/nginx/waf/logformats'
nap_logformats_template = "logformat.tmpl"

staged_config_http_filename = 'conf.d/services.conf'
staged_config_stream_filename = 'stream-conf.d/services.conf'
