# NGINX Configuration Generator

# Main variables
[main]
banner = "NGINX Configuration Generator"
version = "1.0"
url = "https://github.com/fabriziofiorucci/NGINX-Config-Generator"

# Templates
[templates]
root_dir = "../templates"
nginxmain = "nginx-conf/nginx.conf"
mimetypes = "nginx-conf/mime.types"

httpconf = "http.tmpl"
streamconf = "stream.tmpl"
configmap = "configmap.tmpl"
logformat = "logformat.tmpl"

# API Server configuration
[apiserver]
host = "0.0.0.0"
port = 5000

# Staged configuration for NGINX Management Suite
[nms]
config_dir = '/etc/nginx'
certs_dir = '/etc/nginx/ssl'
nap_policies_dir = '/etc/nginx/waf/policies'
nap_logformats_dir = '/etc/nginx/waf/logformats'
staged_config_http_filename = 'conf.d/services.conf'
staged_config_stream_filename = 'stream-conf.d/services.conf'