# NGINX Declarative API

# Main variables
[main]
banner = "NGINX Declarative API"
version = "3.1.0"
url = "https://github.com/fabriziofiorucci/NGINX-Declarative-API"

# Templates
[templates]
root_dir = "../templates"
nginxmain = "nginx-conf/nginx.conf"
mimetypes = "nginx-conf/mime.types"

httpconf = "http.tmpl"
apigwconf = "apigateway.tmpl"
streamconf = "stream.tmpl"
configmap = "configmap.tmpl"

# API Server configuration
[apiserver]
host = "0.0.0.0"
port = 5000

# Redis backend for CI/CD automation
[redis]
host = "redis"
port = 6379

# Devportal helper
[devportal]
host = "devportal"
port = 5001
uri = "/v1/devportal"

# Staged configuration for NGINX Management Suite
[nms]
config_dir = '/etc/nginx'
certs_dir = '/etc/nginx/ssl'
devportal_dir = '/etc/nginx/devportal'

# Time to wait to get status after committing a staged config
staged_config_publish_waittime = 2

# API v0 & V1
nap_policies_dir = '/etc/nginx/waf/policies'
nap_logformats_dir = '/etc/nginx/waf/logformats'
nap_logformats_template = "logformat.tmpl"

# API v2 - support for v2 Policy Compiler
nap_policies_dir_pum = '/etc/nms'
nap_logformats_dir_pum = '/etc/nms'

# Staged configuration filenames
staged_config_http_filename = 'conf.d/services.conf'
staged_config_stream_filename = 'stream-conf.d/services.conf'
