version: "3.2"

volumes:
  redis_data:

services:
  redis:
    image: redis
    user: "${USERID}:${USERGROUP}"
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data:rw

  devportal:
    image: fiorucci/nginx-declarative-api-devportal:latest
    user: "${USERID}:${USERGROUP}"
    container_name: "devportal"
    restart: always
    ports:
      - "5001:5000"

  nginx-dapi:
    image: fiorucci/nginx-declarative-api:latest
    user: "${USERID}:${USERGROUP}"
    container_name: "nginx-dapi"
    restart: always
    depends_on:
      - redis
    ports:
      - "5000:5000"
