version: "3.9"

volumes:
  redis_data:

services:
  redis:
    image: redis
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dapi-network
    volumes:
      - redis_data:/data:rw

  devportal:
    image: nginx-declarative-api-devportal
    build:
      context: ../devportal/redocly
      dockerfile: Dockerfile
    user: "${USERID}:${USERGROUP}"
    container_name: "devportal"
    restart: always
    ports:
      - "5001:5000"
    networks:
      - dapi-network

  nap-compiler:
    profiles:
      - nap
    image: nginx-declarative-api-nap-compiler
    build:
      context: ../app-protect
      dockerfile: Dockerfile
      secrets:
        - nginx-crt
        - nginx-key
      args:
        VERSION_TAG: "${NAP_COMPILER_TAG}"
    container_name: "nap-compiler"
    restart: always
    ports:
      - "5002:5000"
    networks:
      - dapi-network

  nginx-dapi:
    image: nginx-declarative-api
    build:
      context: ../../
      dockerfile: Dockerfile
    user: "${USERID}:${USERGROUP}"
    container_name: "nginx-dapi"
    restart: always
    depends_on:
      - redis
    ports:
      - "5000:5000"
    networks:
      - dapi-network

networks:
  dapi-network:

secrets:
  nginx-crt:
    file: ${NGINX_CERT}
  nginx-key:
    file: ${NGINX_KEY}
